In [3]:
import torch
import numpy as np

This code is based on leveraging the functionality of pytorch for a simple implementation of neural network and a toy model

In [11]:
a = torch.tensor([[1,2,3],[4,5,6]])
print(a**2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [12]:
n = input("Enter any number")
print("The entered number is", n)

The entered number is 4


In [ ]:
arr1 = torch.tensor([[1,2,3,4],[7,8,2,4]]) #4x2 matrix
arr2 = torch.tensor([[1,2],[3,4],[5,6],[7,8]]) #2x4 matrix
res = torch.matmul(arr1, arr2)
print(res)

tensor([[50, 60],
        [69, 90]])


In [ ]:
random_arr1 = torch.randint(100,(10,10))  #generares a 10x10 tensor each randomized in the range of 100
random_arr2 = torch.randint(1000,(10,10)) 

print(torch.matmul(random_arr1, random_arr2))

tensor([[222596, 170105, 212622, 195622, 126857, 216486, 143545, 154424, 222231,
         232332],
        [257564, 259954, 253472, 237823, 231280, 296406, 198109, 206385, 259911,
         346796],
        [297018, 214921, 279660, 236435, 176505, 299089, 227346, 283217, 285594,
         291476],
        [265528, 257088, 278601, 278242, 219902, 320955, 202906, 200146, 270367,
         336259],
        [341672, 249603, 376617, 361312, 199355, 275566, 263821, 280417, 269732,
         410586],
        [287434, 290225, 355204, 292672, 246540, 385681, 265790, 207525, 338382,
         389765],
        [399204, 307878, 419695, 371136, 273791, 421757, 307236, 297697, 422356,
         442111],
        [192148, 157246, 197827, 203159, 161702, 215316, 121300, 135953, 215725,
         253112],
        [243779, 151198, 229877, 247100, 139390, 221399, 174526, 178944, 196718,
         260217],
        [316487, 237527, 357616, 318592, 191329, 292048, 242779, 241157, 286271,
         397889]])
